### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rTOC'

### ISSUE THREAD

**Issue by Da5hes** [a0x77n/chucky-ng#17]
hi

when trying to run chucky as per the instructions i've encountered the following error:

[3/920]:JobSet(2/36)Job (1/27): ....
Traceback (most recent call last):
  File "../chucky/chucky.py", line 247, in <module>
    Chucky().execute()
  File "../chucky/chucky.py", line 208, in execute
    flag=self.analyzeJobSet(jobset,description,jobcount)
  File "../chucky/chucky.py", line 235, in analyzeJobSet
    self.engine.analyze(job)        
  File "/chucky/chucky_engine.py", line 45, in analyze
    nearestNeighbors,s0,s1,s2,s3, = self._getKNearestNeighbors()
  File "/chucky/chucky_engine.py", line 90, in _getKNearestNeighbors
    return self.knn.getNearestNeighbors(self.job.function, symbolUsers)
  File "/chucky/nearestNeighbor/NearestNeighborSelector.py", line 54, in getNearestNeighbors
    ids,m0,m1,m2,m3 = knn.getSimilarContextNeighborsFor(str(nodeId))
  File "/chucky/CallerKNN.py", line 98, in getSimilarContextNeighborsFor
    validNeighbors = [self.emb.rTOC[str(x)] for x in validNeighborIds]
AttributeError: 'NoneType' object has no attribute 'rTOC'

**Comment by stuartly** [comment]
I meet the same problem.
